config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'about' => 'welcome#about'
  get 'show' => 'users#show'
  get 'manage_account' => 'charges#new'

  resources :wikis do
    resources :collaborators
  end
  resources :charges, only: [:new, :create]
  get 'downgrade' => 'charges#downgrade'
  get 'remove_collaborator' => 'collaborators#destroy'
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/charge.rb
class Charge < ApplicationRecord
  belongs_to :user
end

app/models/collaborator.rb
class Collaborator < ApplicationRecord
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :wikis
  has_many :charges
  has_many :collaborators
  has_many :collaborations, through: :collaborators, source: :wiki

  after_initialize :standardizer

  def standard?
    role == 'standard'
  end

  def premium?
    role == 'premium'
  end

  def admin?
    role == 'admin'
  end

  def collaborations
      wikis = []
      Collaborator.where(user: self).each do |collaboration|
        wikis << Wiki.find(collaboration.wiki_id)
      end
      wikis
    end
    
  private

  def standardizer
    self.role ||= 'standard'
  end
end

app/models/wiki.rb
class Wiki < ApplicationRecord
  belongs_to :user
  has_many :collaborators
  has_many :collaborations, through: :collaborators, source: :user

  validates :title, length: { minimum: 1 }, presence: true
  validates :body, length: { minimum: 1 }, presence: true

  def public?
    private == false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def collaboration(user, wiki)
    @collaborator = Collaborator.new
    @collaborator.user = user
    @collaborator.wiki = wiki

    if @collaborator.save
      flash[:notice] = "Collaborations were successfully added."
    else
      flash[:notice] = "An error has occured, please try again later."
    end
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @stripe_btn_data = {
      key: Rails.configuration.stripe[:publishable_key].to_s,
      description: "Upgrade Account - #{current_user.email}",
      amount: 1500
    }
   end

  def create
    # Creates a Stripe Customer object, for associating
    # with the charge
    token = params[:stripeToken]
    customer = Stripe::Customer.create(
      email: current_user.email,
      source: token
    )

    # Where the real magic happens
    charge = Stripe::Charge.create(
      customer: customer.id, # Note -- this is NOT the user_id in your app
      amount: 1500,
      description: "Upgrade Account - #{current_user.email}",
      currency: 'usd'
    )
    if charge.present?
      @charge = Charge.new
      @charge.user = current_user
      @charge.amount = charge.amount
      @charge.successful = true

      if @charge.save
        current_user.update_attributes(role: 'premium')
        if current_user.role == 'premium'
          flash[:notice] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again."
          redirect_to manage_account_path(current_user) # or wherever
        else
          flash[:notice] = 'Sorry, something went wrong. Please try again later'
          redirect_to manage_account_path(current_user)
        end
      else
        flash[:notice] = 'Sorry, something went wrong. Please try again later'
        redirect_to manage_account_path(current_user)
      end
    end
   # Stripe will send back CardErrors, with friendly messages
   # when something goes wrong.
   # This `rescue block` catches and displays those errors.
   rescue Stripe::CardError => e
     flash[:alert] = e.message
     redirect_to manage_account_path
   end

  def downgrade
  current_user.update_attributes(role: 'standard')
  if current_user.standard?
    flash[:notice] = 'Ya basic'
    current_user.wikis.each do |wiki|
      wiki.update_attribute(:private, false)
    end
    redirect_to manage_account_path(current_user)
  else
    flash[:notice] = 'Sorry, something went wrong. Please try again later'
    redirect_to manage_account_path(current_user)
  end
 end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  def create
  #  @collaborator = Collaborator.new
  @collaboration.user = params[:user]
  @collaboration.wiki = params[:wiki]

     if @collaboration.save
       flash[:notice] = "Collaborations were successfully added."
       redirect_to @wiki
     else
       flash[:notice] = "An error has occured, please try again later."
       redirect_to @wiki
     end
 end

 def destroy
   @wiki = Wiki.find(params[:my_params][:wiki_id])
     @collaboration = Collaborator.find_by(user_id: params[:my_params][:user_id], wiki_id: params[:my_params][:wiki_id])

     if @collaboration.destroy
       flash[:notice] = "Collaboration was removed successfully."
       redirect_to @wiki
     else
       flash.now[:alert] = "There was an error deleting the topic."
       redirect_to @wiki
     end
   end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def show
    @user = current_user
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  def index
    @wikis = Wiki.all
  end

  def show
    @wiki = Wiki.find(params[:id])
    @collabs = Collaborator.where(wiki_id: @wiki.id)
    collaborator_list = []
    @collabs.each do |collab|
      iduser = collab.user_id
      collaboration_user = User.where(id: iduser).first
      collaborator_list.push(collaboration_user)
    end
    @collaborations = collaborator_list
  end

  def new
    @wiki = Wiki.new
  end

  def edit
    @wiki = Wiki.find(params[:id])
  end

  def create
    @wiki = Wiki.new
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.private = params[:wiki][:private]
    @wiki.user = current_user

    if @wiki.save
      unless params[:wiki][:collaborations] == ""
        user_list = params[:wiki][:collaborations]
        user_list.split(",").each do |email|
          user = User.where(email: email).first
          @my_collab = collaboration(user, @wiki)
        end
      end
      flash[:notice] = 'Wiki was saved.'
      redirect_to @wiki
    else
      flash.now[:alert] = 'There was an error saving the wiki. Please try again.'
      render :new
    end
  end

  def update
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.private = params[:wiki][:private]


    if @wiki.save
      unless params[:wiki][:collaborations] == ""
        user_list = params[:wiki][:collaborations]
        user_list.split(",").each do |email|
          user = User.where(email: email).first
          @my_collab = collaboration(user, @wiki)
        end
      end
      flash[:notice] = 'Wiki was updated.'
      redirect_to @wiki
    else
      flash.now[:alert] = 'There was an error saving the wiki. Please try again.'
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to action: :index
    else
      flash.now[:alert] = 'There was an error deleting the wiki.'
      render :show
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      disable_indented_code_blocks: true,
      strikethrough: true,
      highlight: true,
      underline: true,
      quote: true,
      footnotes: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
<%if current_user.standard? %>
  <h1>Upgrade your account</h1>
  <div class="container">
  <%= form_tag charges_path do %>
      <h3> For only $15 you can upgrade to a premium account<h3>
      <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
  <% end %>
  </div>
<%else%>
  <h1>Downgrade your account</h1>
  <div class="container">
      <h4> Downgrade to a standard account?<h4>
      <%= link_to "Downgrade", downgrade_path, class: 'btn btn-danger', data: { confirm: 'Are you for realz?' } %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocipedia</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
       <ul class="nav nav-tabs">
         <li><%= link_to "Bloccit", root_path %></li>
         <li><%= link_to "About", about_path %></li>
         <li><%= link_to "Wikis", wikis_path %></li>
       </ul>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
       <% if user_signed_in? %>
        Signed in as: <strong><%= current_user.email %></strong> |
   <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %> -
        <%= link_to "Manage Account", manage_account_path, :class => 'navbar-link' %>
 <% else %>
   <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
   <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
 <% end %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/welcome/about.html.erb
<h1>Welcome to Bloccit</h1>
<p>I built this with my hands, and my brain.</p>

app/views/welcome/index.html.erb
<br>
 <div class="jumbotron">
   <h1>Blocipedia</h1>
   <p>Blocipedia is a resource for sharing links with your friends!</p>
   <p>
   </p>
 </div>

 <div class="row">
   <div class="col-md-4">
     <h2>Solves world hunger</h2>
     <p>Bloccit will deliver food and water to those in need, all over the world.</p>
   </div>
   <div class="col-md-4">
     <h2>Eliminates poverty</h2>
     <p>Bloccit will deliver money and education to those in need, all over the world.</p>
   </div>
   <div class="col-md-4">
     <h2>Makes you better looking</h2>
     <p>Bloccit will make you better looking: it's scientifically proven to make men look like Ryan Gosling and women look like Shakira.</p>
   </div>
 </div>

app/views/wikis/_form.html.erb
<%= form_for [@wiki] do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
  </div>
  <% unless current_user.standard? %>
    <div class="form-group">
      <%= f.label :private, class: 'checkbox' do %>
      <%= f.check_box :private %> Private wiki
      <% end %>
    </div>
  <%end%>

         <div class="form-group">
           <%= f.label :collaborations  %>
           <%= f.text_field :collaborations,
                             class: 'form-control',
                             placeholder: "Enter user emails (separated by commas)" %>
        </div>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
  <% end %>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for wikis</p>
     <ul>
       <li>Does it float?</li>
       <li>No one cares about your cat</li>
       <li>The incessant use of hashtags will get you banned.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= render partial: 'form', locals: { wiki: @wiki} %>
   </div>
 </div>

app/views/wikis/index.html.erb
<h1>Wikis</h1>
<div class="row">
   <div class="col-md-8">
     <% @wikis.each do |wiki| %>
      <%if (wiki.private && wiki.user_id == current_user.id) || !wiki.private || wiki.collaborations.include?(current_user)%>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to markdown(wiki.title), wiki %>
          </h4>
        </div>
      </div>
      <%end%>
     <% end %>
   </div>
   <div class="col-md-4">
     <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
   </div>
 </div>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for wikis</p>
     <ul>
       <li>Does it float?</li>
       <li>No one cares about your cat</li>
       <li>The incessant use of hashtags will get you banned.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= render partial: 'form', locals: { wiki: @wiki} %>
   </div>
 </div>

app/views/wikis/show.html.erb
<div class="row">
   <div class="col-md-8">
     <h1>
          <%= markdown(@wiki.title) %> <br>
          <small>
            submitted <%= time_ago_in_words(@wiki.created_at) %> ago by <%= @wiki.user.email %>
          </small>
      </h1>
        <p><%= markdown(@wiki.body) %></p>
        <div class="col-md-4">
          <% if current_user.role == 'admin' || current_user.role == 'premium' %>
          <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
          <%= link_to "Delete Post", [@wiki], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this wiki?' } %>
          <%end%>
        </div>
      </div>
    </div>
 <% if @collaborations.count > 0 %>
    <div class="media">
      <div class="media-body">
        Contributing Users:
        <% @collaborations.each do |collab| %>
        <h4 class="media-heading">
          <%= collab.email %>
          <%= link_to "Remove", remove_collaborator_path(:my_params => { :user_id => collab.id, :wiki_id => @wiki.id }), class: 'btn btn-danger', data: { confirm: 'Are you sure you want to remove this collaboration?' } %>
        </h4>
        <% end %>
      </div>
    </div>
 <% end %>